addons:
  code_climate:
    repo_token: ebe1bcad44d872643a5b1b85cabed2ca259fe13d25f8da3b220200e5dad0694c

after_success:
  - bundle exec codeclimate-test-reporter

branches:
  except:
    - gh-pages

cache: bundler

env:
  - COVERAGE=true

language: ruby

notifications:
  email:
    - dev@bitaculous.com

rvm:
  - 2.3.3
  - 2.4.0

sudo: false